// Independent provider-verifier probes. All fetches are controlled in-memory HTTP responses.
import {test,after} from 'node:test';
import {assertNoExternalNetworkAttempts} from './network-guard.mjs';
after(assertNoExternalNetworkAttempts);
import assert from 'node:assert/strict';
import {generateKeyPairSync,sign} from 'node:crypto';
import {createVerifier} from '../experiments/atomic-command-poc/service/auth.mjs';
const time=1800000000000,issuer='https://independent.cloudflareaccess.com';
const config={issuer,jwksUrl:issuer+'/cdn-cgi/access/certs',humanAudience:'human-aud',machineAudience:'machine-aud',jwksCacheMs:10000,jwksTimeoutMs:80};
const a=generateKeyPairSync('rsa',{modulusLength:2048}),b=generateKeyPairSync('rsa',{modulusLength:2048});
const jwk=(pair,kid)=>({...pair.publicKey.export({format:'jwk'}),kid,alg:'RS256',use:'sig'});
const ka=jwk(a,'a'),kb=jwk(b,'b');
function token(claims={},header={},pair=a,rawClaims){const h=Buffer.from(JSON.stringify({alg:'RS256',kid:'a',typ:'JWT',...header})).toString('base64url');const p=Buffer.from(rawClaims??JSON.stringify({iss:issuer,aud:['human-aud'],sub:'stable-human-subject',type:'app',iat:time/1000-10,nbf:time/1000-10,exp:time/1000+3600,...claims})).toString('base64url');return `${h}.${p}.${sign('RSA-SHA256',Buffer.from(h+'.'+p),pair.privateKey).toString('base64url')}`;}
const request=(t=token(),extra={})=>new Request('https://app.invalid/',{headers:{'cf-access-jwt-assertion':t,...extra}});
const denied=(promise,code='UNAUTHENTICATED',status=401)=>assert.rejects(promise,e=>e.code===code&&e.status===status);
function fixture(options={}){let now=time,count=0,document={keys:[ka],public_cert:{kid:'a',cert:'unused'},public_certs:[]};const calls=[];let fetchImpl=options.fetchImpl??(async(url,init)=>{count++;calls.push({url,init});return Response.json(document);});const verify=createVerifier({...config,...options.config},{fetchImpl,now:()=>now});return {verify,calls,get count(){return count;},setNow:v=>{now=v;},setDocument:d=>{document=d;}};}
test('official Access app shape uses issuer/subject and no provider app IDs',async()=>{const f=fixture(),v=await f.verify(request(),'human');assert.equal(v.authMethod,'cloudflare_access');assert.equal(v.subject,'stable-human-subject');for(const k of ['principalId','credentialId','workspaceId','email','roles'])assert.equal(v[k],undefined);assert.equal(v.credentialExpiresAt,time+3600000);});
test('multi-audience official token requires pinned audience and ignores display claims',async()=>{const f=fixture();assert.equal((await f.verify(request(token({aud:['other','human-aud'],email:'different@example.invalid',roles:['owner'],cid:'forged'})),'human')).subject,'stable-human-subject');await denied(f.verify(request(token({aud:['other']})),'human'));});
test('expiry is checked again after JWKS fetch, not only before awaiting',async()=>{let now=time;const verify=createVerifier(config,{now:()=>now,fetchImpl:async()=>{now=time+2000;return Response.json({keys:[ka]});}});await denied(verify(request(token({exp:time/1000+1})),'human'),'SESSION_EXPIRED');});
test('wrong issuer, type, audience, time and subject fail before fetching any keys',async()=>{const f=fixture();for(const claims of [{iss:issuer+'/'},{type:'org'},{aud:'human-aud'},{aud:[]},{aud:['human-aud','human-aud']},{sub:''},{sub:'\u0000evil'},{iat:time/1000+1},{nbf:time/1000+1},{exp:'1800000010'},{exp:1e100},{exp:time/1000-20},{common_name:'service.access'}])await denied(f.verify(request(token(claims)),'human'));assert.equal(f.count,0);});
test('header algorithm, critical extension and attacker key location are rejected without fetch',async()=>{const f=fixture();for(const header of [{alg:'none'},{alg:'HS256'},{crit:['b64'],b64:false},{jku:'https://attacker.invalid/keys'},{jwk:ka},{x5u:'https://attacker.invalid/cert'},{kid:''},{kid:'a\n'},{typ:'different+jwt'}])await denied(f.verify(request(token({},header)),'human'));assert.equal(f.count,0);});
test('duplicate security JSON members, malformed base64url and oversized tokens are refused',async()=>{const f=fixture();await denied(f.verify(request(token({}, {},a,'{"iss":"wrong","iss":"'+issuer+'","aud":["human-aud"],"sub":"s","type":"app","iat":1799999990,"nbf":1799999990,"exp":1800001000}')),'human'));const t=token();for(const corrupt of [t+'=',t.replace('.', '=.'),t+'.part','x'.repeat(8193),'..',t.replace(/^[^.]+/,'A')])await denied(f.verify(request(corrupt),'human'));assert.equal(f.count,0);});
test('bad signature cannot gain claims or trigger repeated key refresh',async()=>{const f=fixture();await denied(f.verify(request(token({}, {},b)),'human'));assert.equal(f.count,1);await denied(f.verify(request(token({}, {},b)),'human'));assert.equal(f.count,1);});
test('cookie-only, assertion-only and exact matching copies work without custom cookies',async()=>{const f=fixture(),t=token();for(const headers of [{'cf-access-jwt-assertion':t},{cookie:'CF_Authorization='+t},{'cf-access-jwt-assertion':t,cookie:'CF_Authorization='+t}])assert.equal((await f.verify(new Request('https://app.invalid/',{headers}),'human')).actorKind,'human');});
test('ambiguous credentials do not silently select an identity',async()=>{const f=fixture(),t=token();for(const extra of [{authorization:'Bearer '+t},{cookie:'CF_Authorization='+token({sub:'other'})},{cookie:'CF_Authorization='+t+'; CF_Authorization='+t}])await denied(f.verify(request(t,extra),'human'),'AUTH_CREDENTIAL_AMBIGUOUS');assert.equal(f.count,0);});
test('JWKS request is pinned, credential-free and nonredirecting',async()=>{const f=fixture();await f.verify(request(),'human');assert.equal(f.count,1);const c=f.calls[0];assert.equal(c.url,config.jwksUrl);assert.ok(['error','manual'].includes(c.init.redirect));assert.equal(c.init.credentials,'omit');assert.equal(c.init.cache,'no-store');assert.equal(c.init.method,'GET');assert.deepEqual(Object.keys(c.init.headers),['accept']);});
test('concurrent first requests share one JWKS fetch',async()=>{const f=fixture();await Promise.all(Array.from({length:50},()=>f.verify(request(),'human')));assert.equal(f.count,1);});
test('unknown kids have one global cooldown rather than attacker-sized cache state',async()=>{const f=fixture();await f.verify(request(),'human');for(let i=0;i<20;i++)await denied(f.verify(request(token({}, {kid:'unknown-'+i})),'human'));assert.equal(f.count,1);f.setNow(time+5001);await denied(f.verify(request(token({}, {kid:'unknown-next'})),'human'));assert.equal(f.count,2);});
test('rotation replaces keyset and removes old keys after cache refresh',async()=>{const f=fixture();await f.verify(request(),'human');f.setNow(time+10001);f.setDocument({keys:[kb]});assert.equal((await f.verify(request(token({}, {kid:'b'},b)),'human')).actorKind,'human');await denied(f.verify(request(),'human'));assert.equal(f.count,2);});
test('cache expiry followed by JWKS outage is 503 and never stale success',async()=>{let now=time,count=0;const verify=createVerifier(config,{now:()=>now,fetchImpl:async()=>{count++;if(count>1)return new Response('down',{status:503});return Response.json({keys:[ka]});}});await verify(request(),'human');now=time+10001;await denied(verify(request(),'human'),'AUTH_INFRASTRUCTURE_UNAVAILABLE',503);await denied(verify(request(),'human'),'AUTH_INFRASTRUCTURE_UNAVAILABLE',503);assert.equal(count,2);});
test('provider HTML, redirect, non-200, bad MIME and huge body are infrastructure failures',async()=>{for(const response of [new Response('<html>login</html>',{headers:{'content-type':'text/html'}}),new Response('',{status:302,headers:{location:'https://attacker.invalid'}}),new Response('{}',{status:503}),new Response('{}',{headers:{'content-type':'text/plain'}}),new Response('x'.repeat(65537),{headers:{'content-type':'application/json'}}),new Response('{"keys":[]}',{headers:{'content-type':'application/json','content-length':'999999'}})]){const f=fixture({fetchImpl:async()=>response});await denied(f.verify(request(),'human'),'AUTH_INFRASTRUCTURE_UNAVAILABLE',503);}});
test('malformed, duplicate, weak, wrong-algorithm and private JWKs fail closed',async()=>{const weak=generateKeyPairSync('rsa',{modulusLength:1024});for(const document of [{keys:[]},{keys:[ka,ka]},{keys:[{...ka,alg:'HS256'}]},{keys:[{...ka,use:'enc'}]},{keys:[{...ka,key_ops:['sign']}]},{keys:[{...ka,d:'secret'}]},{keys:[jwk(weak,'a')]},{keys:[{...ka,n:'A'}]},{keys:[{...ka,e:'AAE'}]},{keys:[ka],public_cert:{kid:'a',cert:''}}]){const f=fixture();f.setDocument(document);await denied(f.verify(request(),'human'),'AUTH_INFRASTRUCTURE_UNAVAILABLE',503);}});
test('JWKS response body timeout is bounded even when headers arrive',async()=>{let canceled=false;const f=fixture({fetchImpl:async()=>new Response(new ReadableStream({start(c){c.enqueue(new TextEncoder().encode('{"keys":'));},cancel(){canceled=true;}}),{headers:{'content-type':'application/json'}})});const started=performance.now();await denied(f.verify(request(),'human'),'AUTH_INFRASTRUCTURE_UNAVAILABLE',503);assert.ok(performance.now()-started<1000);assert.equal(canceled,true);});
test('JWKS connection timeout settles even if fetch ignores abort',async()=>{const f=fixture({fetchImpl:()=>new Promise(()=>{})});const started=performance.now();await denied(f.verify(request(),'human'),'AUTH_INFRASTRUCTURE_UNAVAILABLE',503);assert.ok(performance.now()-started<1000);});
test('unsafe provider configuration is refused before network I/O',()=>{for(const change of [{issuer:'http://issuer.invalid'},{issuer:'https://user:password@issuer.invalid'},{jwksUrl:'http://keys.invalid'},{jwksUrl:'https://keys.invalid/#fragment'},{humanAudience:'same',machineAudience:'same'},{jwksCacheMs:4999},{jwksCacheMs:3600001},{jwksTimeoutMs:49},{unexpected:true}])assert.throws(()=>fixture({config:change}),e=>e.code==='AUTH_INFRASTRUCTURE_UNAVAILABLE');});

test('official service-token JWT without app-specific claims maps common_name as machine identity',async()=>{const f=fixture(),t=token({sub:'',common_name:'client-id.access',aud:['machine-aud'],nbf:undefined});const r=new Request('https://app.invalid/',{headers:{authorization:'Bearer '+t}});const v=await f.verify(r,'machine');assert.equal(v.actorKind,'machine');assert.equal(v.subject,'client-id.access');assert.equal(v.authMethod,'cloudflare_access_service_token');assert.equal(v.workspaceId,undefined);assert.equal(v.credentialId,undefined);await denied(f.verify(request(t),'human'));await denied(f.verify(new Request('https://app.invalid/',{headers:{authorization:'Bearer '+token({aud:['machine-aud']})}}),'machine'));});
