// Independent reviewer probes. This harness is not imported by the product.
import {assertNoExternalNetworkAttempts} from './network-guard.mjs';
import {test,before,after,beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import {generateKeyPairSync,sign,randomUUID} from 'node:crypto';
import {createRequire} from 'node:module';
import {readFile} from 'node:fs/promises';
const req=createRequire(new URL('../experiments/atomic-command-poc/package.json',import.meta.url));
const {Miniflare}=req('miniflare');
const root=new URL('../experiments/atomic-command-poc/',import.meta.url);
const origin='https://review-projektor.invalid';
const issuer='https://review-projektor.cloudflareaccess.com';
const jwksUrl=issuer+'/cdn-cgi/access/certs';
const id=n=>`a8000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const wa=id(1),wb=id(2),empty=id(3),unmarked=id(4),wrongSchema=id(5),unknown=id(6);
const human=id(11),machine=id(12),hc=id(13),mc=id(14),project=id(15),issue=id(16),epoch=id(17);
const subject=id(18);
const pair=generateKeyPairSync('rsa',{modulusLength:2048});
const publicJwk={...pair.publicKey.export({format:'jwk'}),kid:'independent-key',alg:'RS256',use:'sig'};
const provider={issuer,jwksUrl,humanAudience:'independent-human-audience',machineAudience:'independent-machine-audience',jwksCacheMs:5000,jwksTimeoutMs:500};
let mf,ns;const stores=new Map();let outbound=[];
function jwt(claims={},header={}){
 const now=Math.floor(Date.now()/1000);
 const payload={iss:issuer,aud:[provider.humanAudience],sub:subject,type:'app',iat:now-20,nbf:now-20,exp:now+600,email:'untrusted-display@example.invalid',identity_nonce:'review-nonce',...claims};
 const h=Buffer.from(JSON.stringify({alg:'RS256',kid:'independent-key',typ:'JWT',...header})).toString('base64url');
 const p=Buffer.from(JSON.stringify(payload)).toString('base64url');
 return h+'.'+p+'.'+sign('RSA-SHA256',Buffer.from(h+'.'+p),pair.privateKey).toString('base64url');
}
function humanHeaders(token=jwt()){return {'cf-access-jwt-assertion':token};}
function machineHeaders(workspace=wa,claims={}){return {authorization:'Bearer '+jwt({aud:[provider.machineAudience],sub:'',common_name:'machine-subject',nbf:undefined,...claims})};}
const path=(workspace=wa)=>`/v1/workspaces/${workspace}`;
const query=(workspace=wa)=>path(workspace)+`/my-issues?workspaceEpoch=${epoch}`;
async function send(url=query(),options={}){const response=await mf.dispatchFetch(origin+url,{headers:humanHeaders(),...options});let body;try{body=await response.json();}catch{body=null;}return {response,body};}
function command(workspace=wa,changes={}){return {schemaVersion:1,workspaceId:workspace,workspaceEpoch:epoch,operationId:randomUUID(),commandType:'Issue.UpdateTitle',entityId:issue,expectedVersion:7,payload:{title:'independent update'},...changes};}
async function write(c=command(),headers={}){return send(path(c.workspaceId)+'/commands',{method:'POST',headers:{...humanHeaders(),origin,'x-projektor-csrf':'same-origin','sec-fetch-site':'same-origin','content-type':'application/json','idempotency-key':c.operationId,...headers},body:JSON.stringify(c)});}
async function sql(workspace,statement,...args){return stores.get(workspace).exec(statement,...args);}
async function checkNoEffects(workspace=wa){assert.equal((await sql(workspace,'SELECT version FROM issue WHERE id=?',issue))[0].version,7);for(const table of ['activity','outbox'])assert.equal((await sql(workspace,`SELECT COUNT(*) n FROM ${table}`))[0].n,0);}
before(async()=>{
 mf=new Miniflare({cf:false,unsafeInspectDurableObjects:true,name:'product-review',modules:true,scriptPath:new URL('service/entry.mjs',root).pathname,compatibilityDate:'2026-07-30',compatibilityFlags:['nodejs_compat'],modulesRules:[{type:'Text',include:['**/*.sql'],fallthrough:true}],bindings:{APP_ORIGIN:origin,REQUEST_TIMEOUT_MS:1500,BODY_TIMEOUT_MS:250,WORKSPACE_IDS:JSON.stringify([wa,wb,empty,unmarked,wrongSchema]),PROVIDER_CONFIG:JSON.stringify(provider)},durableObjects:{WORKSPACE:{className:'WorkspaceService',useSQLite:true}},outboundService:async request=>{
  outbound.push({url:request.url,method:request.method,authorization:request.headers.get('authorization'),cookie:request.headers.get('cookie')});
  assert.equal(request.url,jwksUrl,'Only the pinned synthetic JWKS endpoint may be called');
  return Response.json({keys:[publicJwk],public_cert:{kid:'independent-key',cert:'mock-unused-cert'},public_certs:[]});
 }});
 await mf.ready;ns=await mf.getDurableObjectNamespace('WORKSPACE');
 for(const workspace of [wa,wb,empty,unmarked,wrongSchema])stores.set(workspace,await mf.unsafeGetDurableObjectStorage('product-review','WorkspaceService',{name:workspace}));
 await sql(unmarked,'CREATE TABLE source_data(id TEXT PRIMARY KEY,value TEXT)');await sql(unmarked,'INSERT INTO source_data VALUES(?,?)','source-id','preserve me');await sql(unmarked,'DROP TABLE service_schema');await mf.unsafeEvictDurableObject('product-review','WorkspaceService',{name:unmarked});
 await sql(wrongSchema,'UPDATE service_schema SET version=999');await mf.unsafeEvictDurableObject('product-review','WorkspaceService',{name:wrongSchema});
 for(const workspace of [wa,wb,empty]){const r=await send(query(workspace));assert.equal(r.body?.error?.code,'STORE_UNINITIALIZED',JSON.stringify(r.body));}
});
after(async()=>{await mf?.dispose();assertNoExternalNetworkAttempts();});
beforeEach(async()=>{
 for(const workspace of [wa,wb]){
  for(const table of ['identity_binding','operation','outbox','activity','issue_read_grant','issue_queue','issue_fts','issue','project_grant','credential','membership','workspace'])await sql(workspace,`DELETE FROM ${table}`);
  await sql(workspace,'INSERT INTO workspace VALUES(?,?,1,0)',workspace,epoch);
  for(const [actor,kind,credential,sub] of [[human,'human',hc,subject],[machine,'machine',mc,'machine-subject']]){
   await sql(workspace,'INSERT INTO membership VALUES(?,?,0,1)',actor,kind);
   await sql(workspace,'INSERT INTO credential VALUES(?,?,?,0,1,1)',credential,actor,Date.now()+3600000);
   await sql(workspace,'INSERT INTO identity_binding VALUES(?,?,?,?,?)',issuer,sub,credential,actor,kind);
   await sql(workspace,'INSERT INTO project_grant VALUES(?,?,1,1)',actor,project);
  }
  await sql(workspace,'INSERT INTO issue VALUES(?,?,?,7,0)',issue,project,workspace===wa?'workspace A secret':'workspace B secret');
  await sql(workspace,'INSERT INTO issue_fts VALUES(?,?)',issue,'workspace secret');
  await sql(workspace,'INSERT INTO issue_queue VALUES(?,?,?,?,?,0)',issue,human,'ready',1,100);
 }
});

test('real Access-shaped JWT without cid/wid/kind authenticates through exact product entry',async()=>{const r=await send();assert.equal(r.response.status,200,JSON.stringify(r.body));assert.equal(r.body.meta.actorId,human);assert.equal(r.body.data.items[0].title,'workspace A secret');assert.equal(r.response.headers.get('cache-control'),'no-store');assert.equal(r.response.headers.get('access-control-allow-origin'),null);});
test('matching Access header plus browser cookie is one credential; mismatched or duplicate is refused',async()=>{const t=jwt(),r=await send(query(),{headers:{...humanHeaders(t),cookie:'CF_Authorization='+t}});assert.equal(r.response.status,200);for(const cookie of ['CF_Authorization='+jwt({sub:id(19)}),'CF_Authorization='+t+'; CF_Authorization='+t]){const denied=await send(query(),{headers:{...humanHeaders(t),cookie}});assert.equal(denied.response.status,401);}});
test('issuer/audience/type and service-token confusion cannot enter human route',async()=>{for(const claims of [{iss:'https://other.cloudflareaccess.com'},{aud:['other-aud']},{type:'org'},{sub:'',common_name:'synthetic.access'},{sub:subject,common_name:'synthetic.access'}]){const r=await send(query(),{headers:humanHeaders(jwt(claims))});assert.equal(r.response.status,401,JSON.stringify(claims));}});
test('signed untrusted app identity/role claims and spoofed headers never replace current binding',async()=>{const r=await send(query(),{headers:{...humanHeaders(jwt({cid:mc,wid:wb,kind:'machine',principalId:machine,role:'owner',scope:'*'})),'x-principal-id':machine,'x-workspace-id':wb,'cf-access-authenticated-user-email':'owner@example.invalid'}});assert.equal(r.response.status,200);assert.equal(r.body.meta.actorId,human);assert.equal(r.body.meta.workspaceId,wa);});
test('public SQL/reset/seed/keys/actor/fault endpoints do not exist',async()=>{for(const suffix of ['sql','reset','seed','keys','identity','actor','fault','admin']){const r=await send(path()+'/'+suffix,{method:'POST',body:'{}'});assert.equal(r.response.status,404,suffix);}for(const method of ['sql','seed','reset','updateTitle','command','issue','myIssues','receipt','getIssues'])await assert.rejects(async()=>await ns.getByName(wa)[method]({principalId:human}));await checkNoEffects();});
test('unknown registry workspace never becomes an authorized empty store',async()=>{const before=(await mf.listDurableObjectIds('WORKSPACE')).length;const r=await send(query(unknown));assert.ok([403,404].includes(r.response.status));assert.equal(r.body.data,undefined);assert.equal((await mf.listDurableObjectIds('WORKSPACE')).length,before);});
test('actual object routing isolates identical entity IDs across two workspace stores',async()=>{const a=await send(),b=await send(query(wb));assert.equal(a.body.data.items[0].title,'workspace A secret');assert.equal(b.body.data.items[0].title,'workspace B secret');assert.equal((await write()).response.status,200);assert.equal((await send(query(wb))).body.data.items[0].title,'workspace B secret');});
test('wrong target object ID is rejected even through direct authenticated DO fetch',async()=>{const r=await ns.getByName(wa).fetch(origin+query(wb),{headers:humanHeaders()});assert.equal(r.status,403);assert.equal((await r.json()).error.code,'WORKSPACE_MISMATCH');});
test('DB workspace mismatch fails closed rather than trusting route alone',async()=>{await sql(wa,'UPDATE workspace SET id=?',unknown);const r=await send();assert.equal(r.response.status,403);assert.equal(r.body.error.code,'WORKSPACE_MISMATCH');});
test('fresh store does not invent workspace, principal or membership',async()=>{const r=await send(query(empty));assert.equal(r.response.status,503);assert.equal(r.body.error.code,'STORE_UNINITIALIZED');for(const table of ['workspace','membership','credential','identity_binding'])assert.equal((await sql(empty,`SELECT COUNT(*) n FROM ${table}`))[0].n,0);});
test('unmarked existing data and unsupported schema are preserved and refused',async()=>{for(const workspace of [unmarked,wrongSchema]){const r=await send(query(workspace));assert.equal(r.response.status,503);assert.equal(r.body.error.code,'STORE_SCHEMA_UNSUPPORTED');}assert.deepEqual(await sql(unmarked,'SELECT * FROM source_data'),[{id:'source-id',value:'preserve me'}]);assert.equal((await sql(unmarked,"SELECT count(*) n FROM sqlite_master WHERE name='service_schema'"))[0].n,0);});
test('revoked membership, credential, read scope, expiry and deleted binding are current on every request',async()=>{for(const [mutate,restore] of [['UPDATE membership SET revoked=1','UPDATE membership SET revoked=0'],['UPDATE credential SET revoked=1','UPDATE credential SET revoked=0'],['UPDATE credential SET can_read=0','UPDATE credential SET can_read=1'],['UPDATE credential SET expires_at=0','UPDATE credential SET expires_at='+String(Date.now()+3600000)]]){assert.equal((await send()).response.status,200);await sql(wa,mutate);const denied=await send();assert.ok([401,403].includes(denied.response.status),mutate);assert.equal(denied.body.data,undefined);await sql(wa,restore);}await sql(wa,'DELETE FROM identity_binding WHERE credential_id=?',hc);assert.equal((await send()).response.status,401);});
test('duplicate human subject mappings are not resolved by arbitrary first row',async()=>{const c=id(20);await sql(wa,'INSERT INTO credential VALUES(?,?,?,0,1,1)',c,machine,Date.now()+60000);await sql(wa,'INSERT INTO identity_binding VALUES(?,?,?,?,?)',issuer,subject,c,machine,'human');assert.equal((await send()).response.status,401);});
test('restricted resource hides list/count/detail and cannot be title-written by a reader',async()=>{await sql(wa,'UPDATE issue_queue SET restricted_read=1');const r=await send();assert.equal(r.response.status,200);assert.equal(r.body.data.total,0);assert.equal((await send(path()+`/issues/${issue}?workspaceEpoch=${epoch}`)).response.status,404);await sql(wa,'INSERT INTO issue_read_grant VALUES(?,?,1)',issue,human);assert.equal((await send()).body.data.total,1);assert.equal((await write()).response.status,403);await checkNoEffects();});
test('all-status query and legitimate empty remain distinct from authorization denial',async()=>{await sql(wa,"UPDATE issue_queue SET status_category='done'");const r=await send();assert.deepEqual(r.body.data,{items:[],nextCursor:null,total:0});assert.equal((await send(query()+'&status=all')).body.data.total,1);await sql(wa,'UPDATE credential SET revoked=1');const denied=await send();assert.equal(denied.response.status,403);assert.equal(denied.body.data,undefined);});
test('machine uses its own principal and cannot consume the human credential channel',async()=>{await sql(wa,'UPDATE issue_queue SET assignee_id=?',machine);const url='/machine'+query();const r=await send(url,{headers:machineHeaders()});assert.equal(r.response.status,200,JSON.stringify(r.body));assert.equal(r.body.meta.actorId,machine);assert.equal(r.body.data.items[0].assignee_kind,'machine');assert.equal((await send(url,{headers:humanHeaders()})).response.status,401);assert.equal((await send(query(),{headers:machineHeaders()})).response.status,401);await sql(wb,'DELETE FROM identity_binding WHERE kind=?','machine');assert.equal((await send('/machine'+query(wb),{headers:machineHeaders()})).response.status,401);});
test('exact same-origin CSRF contract rejects absent/null/foreign origin and fetch-site',async()=>{for(const headers of [{origin:''},{origin:'null'},{origin:'https://attacker.invalid'},{'x-projektor-csrf':''},{'sec-fetch-site':'cross-site'},{origin:origin+', https://attacker.invalid'}]){const r=await write(command(),headers);assert.equal(r.response.status,403,JSON.stringify(headers));}await checkNoEffects();});
test('request URL origin is authoritative; forwarded host cannot repair a foreign host',async()=>{for(const target of ['http://review-projektor.invalid','https://foreign.invalid']){const r=await mf.dispatchFetch(target+query(),{headers:{...humanHeaders(),'x-forwarded-host':'review-projektor.invalid','x-forwarded-proto':'https'}});assert.equal(r.status,403);}await checkNoEffects();});
test('invalid schema/envelope/content type and actor injection leave all business effects absent',async()=>{for(const c of [command(wa,{schemaVersion:99}),command(wa,{principalId:machine}),command(wa,{expectedVersion:undefined}),command(wa,{payload:{title:'x',fault:'after_issue'}})]){const r=await write(c);assert.ok([400,428].includes(r.response.status));}assert.equal((await write(command(),{'idempotency-key':randomUUID()})).response.status,400);assert.equal((await write(command(),{'content-type':'text/plain'})).response.status,415);await checkNoEffects();});
test('concurrent same-ID writes produce one atomic effect and stable receipt',async()=>{const c=command();const results=await Promise.all(Array.from({length:25},()=>write(c)));for(const r of results){assert.equal(r.response.status,200,JSON.stringify(r.body));assert.equal(r.body.data.committedVersion,8);}for(const table of ['activity','outbox','operation'])assert.equal((await sql(wa,`SELECT COUNT(*) n FROM ${table}`))[0].n,1);assert.equal((await sql(wa,'SELECT version FROM issue'))[0].version,8);assert.equal((await send(path()+`/operations/${c.operationId}?workspaceEpoch=${epoch}`)).body.data.outcome,'committed');});
test('write revocation permits read-authorized receipt replay but never a new mutation',async()=>{const c=command();assert.equal((await write(c)).response.status,200);await sql(wa,'UPDATE credential SET can_write=0');assert.equal((await write(c)).response.status,200);assert.equal((await write(command(wa,{expectedVersion:8}))).response.status,403);await sql(wa,'UPDATE project_grant SET can_read=0');assert.equal((await send(path()+`/operations/${c.operationId}?workspaceEpoch=${epoch}`)).response.status,403);});
test('writer fence and epoch mismatch block before business effects',async()=>{await sql(wa,'UPDATE workspace SET active=0');assert.equal((await write()).body.error.code,'STORE_FENCED');await sql(wa,'UPDATE workspace SET active=1');assert.equal((await write(command(wa,{workspaceEpoch:randomUUID()}))).body.error.code,'EPOCH_MISMATCH');await checkNoEffects();});
test('only pinned public JWKS requests were made; no credentials sent to provider',()=>{assert.ok(outbound.length>0);for(const request of outbound){assert.equal(request.url,jwksUrl);assert.equal(request.method,'GET');assert.equal(request.authorization,null);assert.equal(request.cookie,null);}});

test('test-only fault sentinel is an ordinary title in product execution',async()=>{const c=command(wa,{payload:{title:'TEST_ONLY_DROP_AFTER_COMMIT'}}),r=await write(c);assert.equal(r.response.status,200);assert.equal(r.body.data.outcome,'committed');assert.equal((await send()).body.data.items[0].title,'TEST_ONLY_DROP_AFTER_COMMIT');});
test('malformed and duplicated query controls never silently broaden data',async()=>{for(const suffix of ['&workspaceEpoch='+epoch,'&status=open','&status=all&status=all','&limit=01','&limit=101','&limit=1.5','&principalId='+machine,'&projectId=','&cursor=']){const r=await send(query()+suffix);assert.equal(r.response.status,400,suffix);assert.equal(r.body.data,undefined);}});
test('unfinished body times out without a late write, then same-ID complete retry succeeds',async()=>{const c=command(),bytes=JSON.stringify(c);let timer;const stream=new ReadableStream({start(controller){controller.enqueue(new TextEncoder().encode(bytes.slice(0,-1)));timer=setTimeout(()=>{try{controller.enqueue(new TextEncoder().encode('}'));controller.close();}catch{}},600);},cancel(){clearTimeout(timer);}});const started=performance.now();const r=await send(path()+'/commands',{method:'POST',headers:{...humanHeaders(),origin,'x-projektor-csrf':'same-origin','content-type':'application/json','idempotency-key':c.operationId},body:stream,duplex:'half'});assert.equal(r.response.status,408);assert.equal(r.body.error.outcome,'unknown');assert.ok(performance.now()-started<1400);await new Promise(resolve=>setTimeout(resolve,700));clearTimeout(timer);await checkNoEffects();assert.equal((await sql(wa,'SELECT count(*) n FROM operation'))[0].n,0);assert.equal((await write(c)).response.status,200);});
test('whole edge deadline covers slow provider fetch and does not dispatch a workspace later',async()=>{let completed=false;const slow=new Miniflare({cf:false,name:'deadline-review',modules:true,scriptPath:new URL('service/entry.mjs',root).pathname,compatibilityDate:'2026-07-30',compatibilityFlags:['nodejs_compat'],modulesRules:[{type:'Text',include:['**/*.sql'],fallthrough:true}],bindings:{APP_ORIGIN:origin,REQUEST_TIMEOUT_MS:1000,BODY_TIMEOUT_MS:250,WORKSPACE_IDS:JSON.stringify([wa]),PROVIDER_CONFIG:JSON.stringify({...provider,jwksTimeoutMs:2500})},durableObjects:{WORKSPACE:{className:'WorkspaceService',useSQLite:true}},outboundService:async()=>{await new Promise(resolve=>setTimeout(resolve,1600));completed=true;return Response.json({keys:[publicJwk]});}});try{await slow.ready;const started=performance.now(),r=await slow.dispatchFetch(origin+query(),{headers:humanHeaders()});assert.equal(r.status,503);assert.equal((await r.json()).error.code,'TRANSPORT_TIMEOUT');assert.ok(performance.now()-started<1450);await new Promise(resolve=>setTimeout(resolve,900));assert.equal(completed,true);assert.equal((await slow.listDurableObjectIds('WORKSPACE')).length,0);}finally{await slow.dispose();}});
