// Independent probes against the local signed-cookie/workerd/SQLite HTTP harness.
import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {randomUUID} from 'node:crypto';
import {startHarness} from '../experiments/atomic-command-poc/browser-test/server.mjs';
const {chromium}=createRequire(new URL('../experiments/atomic-command-poc/package.json',import.meta.url))('playwright');
let browser;
before(async()=>{browser=await chromium.launch({...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),headless:true,args:['--no-sandbox']});});
after(async()=>{await browser?.close();});
async function setup(t){const h=await startHarness();const context=await browser.newContext();t.after(async()=>{await context.close();await h.close();});await h.login(context,'A');const page=await context.newPage();await page.goto(h.base);await page.waitForFunction(()=>!!window.start);const session=await page.evaluate(()=>fetch('/v1/session').then(r=>r.json()));const options={binding:{principalId:session.principalId,workspaceId:session.workspaceId,workspaceEpoch:session.workspaceEpoch,resourceType:'issue',resourceId:h.ids.issue,editorId:'title',projectAtProtection:h.ids.project,draftId:randomUUID()},template:{schemaVersion:1,workspaceId:session.workspaceId,workspaceEpoch:session.workspaceEpoch,commandType:'Issue.UpdateTitle',entityId:h.ids.issue},dbName:`review-${randomUUID()}`};assert.equal((await page.evaluate(o=>window.start(o),options)).kind,'ready');return{h,context,page,options};}
async function edit(page,text){await page.getByRole('textbox',{name:'Issue title'}).fill(text);assert.equal((await page.evaluate(()=>app.flush())).kind,'protected');}
async function reload(f){await f.page.reload();await f.page.waitForFunction(()=>!!window.start);return f.page.evaluate(o=>window.start(o),f.options);}
const snap=page=>page.evaluate(()=>app.snapshot());

test('CSP permits real Save-button click through to committed operation',async t=>{const f=await setup(t);await edit(f.page,'saved through visible button');await f.page.getByRole('button',{name:'Save',exact:true}).click();await f.page.waitForFunction(()=>app.value?.journal?.state==='committed',{},{timeout:10000});assert.equal((await snap(f.page)).draft.ack,(await snap(f.page)).draft.revision);assert.equal((await f.h.control('effects')).issue.title,'saved through visible button');});

test('newly inaccessible resource locks the DOM after rejected NOT_FOUND',async t=>{const f=await setup(t);await edit(f.page,'must not remain disclosed');await f.h.control('revokeCurrentProject');await f.page.evaluate(()=>app.save());assert.equal((await snap(f.page)).locked,true);assert.equal(await f.page.getByRole('textbox',{name:'Issue title'}).inputValue(),'');});

test('Retry-After beyond total budget settles promptly without early replay',async t=>{const f=await setup(t);await edit(f.page,'overload retained');let posts=0;await f.page.route('**/commands',route=>{posts++;return route.fulfill({status:503,headers:{'retry-after':'120'},contentType:'text/plain',body:'busy'});});assert.equal((await f.page.evaluate(()=>app.save())).kind,'ambiguous');const result=await f.page.evaluate(()=>Promise.race([app.recover(),new Promise(resolve=>setTimeout(()=>resolve({kind:'review-timeout'}),3500))]));assert.notEqual(result.kind,'review-timeout');assert.equal(posts,1);assert.equal((await snap(f.page)).draft.text,'overload retained');});

test('clean acknowledged draft adopts newer authorized resource value',async t=>{const f=await setup(t);await edit(f.page,'first saved title');assert.equal((await f.page.evaluate(()=>app.save())).kind,'committed');await f.h.control('sql','UPDATE issue SET title=?,version=version+1 WHERE id=?',['another editor current title',f.h.ids.issue]);assert.equal((await f.page.evaluate(()=>app.revalidate())).kind,'ready');assert.equal((await snap(f.page)).draft.text,'another editor current title');assert.equal((await snap(f.page)).draft.baseVersion,(await f.h.control('effects')).issue.version);});

test('same-principal scope reduction becomes a non-expanding renewal ceiling',async t=>{const f=await setup(t);await edit(f.page,'preserve on scope changes');await f.h.control('sql','UPDATE credential SET can_write=0 WHERE principal_id=?',[f.h.ids.actorA]);assert.equal((await f.page.evaluate(()=>app.revalidate())).kind,'ready');await f.h.control('sql','UPDATE credential SET can_write=1 WHERE principal_id=?',[f.h.ids.actorA]);await f.page.evaluate(()=>app.revalidate());assert.equal((await snap(f.page)).locked,true);assert.equal(await f.page.getByRole('textbox',{name:'Issue title'}).inputValue(),'');});

test('delayed key response after identity erase cannot restore memory or keys',async t=>{const f=await setup(t);await edit(f.page,'late secret');let release;const gate=new Promise(r=>release=r);let entered;const waiting=new Promise(r=>entered=r);await f.page.route('**/v1/draft-keys',async route=>{entered();await gate;await route.continue();});await f.page.evaluate(()=>{window.reviewPending=app.revalidate();});await waiting;await f.page.evaluate(()=>app.lock('identity-changed',{erase:true}));release();await f.page.evaluate(()=>window.reviewPending);assert.equal((await snap(f.page)).locked,true);assert.equal(await f.page.evaluate(()=>app.value),null);assert.equal(await f.page.evaluate(()=>app.vault.keys.size),0);});

test('receipt lookup budget survives successive reloads',async t=>{const f=await setup(t);await edit(f.page,'unknown operation');await f.page.route('**/commands',route=>route.abort('connectionfailed'));assert.equal((await f.page.evaluate(()=>app.save())).kind,'ambiguous');await f.page.evaluate(async()=>{app.value.journal.receipts=5;await app.flush();});let receipts=0;await f.page.route('**/operations/**',route=>{receipts++;return route.continue();});await reload(f);assert.equal(receipts,1);assert.equal((await snap(f.page)).draft.journal.receipts,6);await reload(f);assert.equal(receipts,1);assert.equal((await snap(f.page)).draft.journal.receipts,6);});

test('thrown navigation callback settles with draft retained',async t=>{const f=await setup(t);await edit(f.page,'stay on this page');const result=await f.page.evaluate(()=>app.navigateRecovery(()=>{throw Error('synthetic navigation failure');}));assert.equal(result.mayNavigate,true);assert.equal((await snap(f.page)).busy,false);assert.equal((await snap(f.page)).status,'recovery-stopped');assert.equal((await snap(f.page)).draft.text,'stay on this page');});

test('invalid committed receipt is never reported as successful recovery',async t=>{const f=await setup(t);await edit(f.page,'unacknowledged draft');await f.page.route('**/commands',route=>route.abort('connectionfailed'));assert.equal((await f.page.evaluate(()=>app.save())).kind,'ambiguous');const command=(await snap(f.page)).draft.journal.command;await f.page.route('**/operations/**',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({data:{outcome:'committed',effectApplied:true,entityId:f.h.ids.issue,committedVersion:0,commitSeq:1},meta:{actorId:f.h.ids.actorA,workspaceId:f.h.ids.workspace,operationId:command.operationId}})}));const result=await f.page.evaluate(()=>app.recover());assert.notEqual(result.kind,'committed');assert.ok((await snap(f.page)).draft.ack<(await snap(f.page)).draft.revision);});

test('repeated session verification cannot silently adopt and overwrite a conflicting tab branch',async t=>{const f=await setup(t);const second=await f.context.newPage();await second.goto(f.h.base);await second.waitForFunction(()=>!!window.start);assert.equal((await second.evaluate(o=>window.start(o),f.options)).kind,'ready');await edit(f.page,'tab A protected branch');await second.getByRole('textbox',{name:'Issue title'}).fill('tab B conflicting branch');assert.equal((await second.evaluate(()=>app.flush())).kind,'protection-failed');await second.evaluate(()=>app.revalidate());await second.evaluate(()=>app.revalidate());assert.equal((await snap(second)).locked,true);assert.equal((await second.evaluate(()=>app.flush())).kind,'protection-failed');assert.equal((await reload(f)).kind,'ready');assert.equal((await snap(f.page)).draft.text,'tab A protected branch');});
