// Independent real Chromium probes. Synthetic key providers isolate browser
// storage/lifecycle invariants; server authorization is covered separately.
import {createServer} from 'node:http';
import {readFile,access} from 'node:fs/promises';
import {dirname,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../experiments/atomic-command-poc');
const {chromium}=createRequire(resolve(root,'package.json'))('playwright');
const server=createServer(async(req,res)=>{try{const path=new URL(req.url,'http://localhost').pathname;if(path==='/'){res.setHeader('Content-Type','text/html');res.end('<!doctype html><title>Independent real-browser vault probes</title>');return;}const file=resolve(root,'.'+path);if(!file.startsWith(root+'/'))throw Error('bad path');res.setHeader('Content-Type','text/javascript');res.end(await readFile(file));}catch{res.statusCode=404;res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;
const executablePath=process.env.CHROMIUM_PATH;
let browser;const results=[];
async function probe(name,run){const context=await browser.newContext();try{const page=await context.newPage();await page.goto(origin);const result=await run(page,context);results.push({name,...result});console.log(JSON.stringify(results.at(-1)));}catch(e){results.push({name,pass:false,error:e.message});console.log(JSON.stringify(results.at(-1)));}finally{await context.close();}}
async function init(page,dbName){await page.evaluate(async dbName=>{const{DraftVault}=await import('/browser/draft-vault.mjs');window.binding={principalId:'A',workspaceId:'W',workspaceEpoch:'E',draftId:'D',resourceId:'I',resourceType:'issue',projectAtProtection:'P',editorId:'title'};window.session={sessionId:'S',principalId:'A',workspaceId:'W',workspaceEpoch:'E',expiresAt:Date.now()+60000};window.keyReply=()=>({session:window.session,keyId:'K',key:btoa('x'.repeat(32)),leaseExpiresAt:Date.now()+30000});window.vault=new DraftVault({dbName,keyProvider:async()=>keyReply()});},dbName);}
try{
 browser=await chromium.launch({...(executablePath?{executablePath}:{}),headless:true,args:['--no-sandbox']});
 await probe('late key reply cannot repopulate cleared cache',async page=>page.evaluate(async()=>{const{DraftVault}=await import('/browser/draft-vault.mjs');const binding={principalId:'A',workspaceId:'W',workspaceEpoch:'E',draftId:'D',resourceId:'I',resourceType:'issue',projectAtProtection:'P',editorId:'title'};const session={sessionId:'S',principalId:'A',workspaceId:'W',workspaceEpoch:'E',expiresAt:Date.now()+60000};let deliver;const provider=new Promise(r=>deliver=r);const vault=new DraftVault({keyProvider:()=>provider});const request=vault.key(binding,null,session);vault.clearKeys();deliver({session,keyId:'K',key:btoa('x'.repeat(32)),leaseExpiresAt:Date.now()+30000});let error;try{await request;}catch(e){error=e.message;}return{pass:vault.keys.size===0,cacheSize:vault.keys.size,error};}));
 await probe('equal revision from stale tab cannot overwrite newer protected draft',async(page,context)=>{const second=await context.newPage();await second.goto(origin);await init(page,'cross-tab-review');await init(second,'cross-tab-review');await page.evaluate(()=>vault.persist(binding,{text:'baseline',revision:1,baseVersion:1},session,()=>true));await second.evaluate(()=>vault.restore(binding,session,()=>true));await page.evaluate(()=>vault.persist(binding,{text:'newest protected edit',revision:2,baseVersion:1},session,()=>true));const stale=await second.evaluate(async()=>{try{await vault.persist(binding,{text:'stale other tab edit',revision:2,baseVersion:1},session,()=>true);return'protected';}catch(e){return e.message;}});const restored=await page.evaluate(()=>vault.restore(binding,session,()=>true));return{pass:restored.text==='newest protected edit',staleResult:stale,restored};});
 await probe('shared discard fences stale writer from another session',async(page,context)=>{const second=await context.newPage();await second.goto(origin);await init(page,'discard-review');await init(second,'discard-review');await second.evaluate(()=>session.sessionId='S2');await page.evaluate(()=>vault.persist(binding,{text:'discard me',revision:1,baseVersion:1},session,()=>true));await second.evaluate(()=>vault.restore(binding,session,()=>true));await second.evaluate(()=>vault.tombstone(session.sessionId,session.principalId,{discard:true}));let writeResult=await page.evaluate(async()=>{try{await vault.persist(binding,{text:'resurrected',revision:2,baseVersion:1},session,()=>true);return'protected';}catch(e){return e.message;}});const record=await second.evaluate(()=>vault.get(binding));return{pass:record===null,writeResult,recordPresent:record!==null};});
 await probe('restore cannot adopt a deletion generation and resurrect stale memory',async(page,context)=>{const second=await context.newPage();await second.goto(origin);await init(page,'discard-restore-review');await init(second,'discard-restore-review');await second.evaluate(()=>session.sessionId='S2');await page.evaluate(()=>vault.persist(binding,{text:'discard me',revision:1,baseVersion:1},session,()=>true));await second.evaluate(()=>vault.restore(binding,session,()=>true));await second.evaluate(()=>vault.tombstone(session.sessionId,session.principalId,{discard:true}));const attempts=await page.evaluate(async()=>{let restoreResult,writeResult;try{restoreResult=await vault.restore(binding,session,()=>true);}catch(e){restoreResult=e.message;}try{await vault.persist(binding,{text:'stale retained memory',revision:2,baseVersion:1},session,()=>true);writeResult='protected';}catch(e){writeResult=e.message;}return{restoreResult,writeResult};});const record=await second.evaluate(()=>vault.get(binding));return{pass:record===null,...attempts,recordPresent:record!==null};});
 for(const variant of ['non-finite lease','expired lease','AES-128 key','unexpected replacement key ID'])await probe(`${variant} is rejected`,async page=>{await init(page,'shape-review');return page.evaluate(async variant=>{const{DraftVault}=await import('/browser/draft-vault.mjs');const bad={...keyReply(),...(variant==='non-finite lease'?{leaseExpiresAt:NaN}:variant==='expired lease'?{leaseExpiresAt:Date.now()-1}:variant==='AES-128 key'?{key:btoa('x'.repeat(16))}:{keyId:'different-key'})};const v=new DraftVault({keyProvider:async()=>bad});try{await v.key(binding,variant==='unexpected replacement key ID'?'K':null,session);return{pass:false,accepted:true};}catch(e){return{pass:true,error:e.message};}},variant);});
 await probe('ciphertext at rest hides body, digest and key; nonces change',async page=>{await init(page,'at-rest-review');return page.evaluate(async()=>{const text='独立レビュー secret\r\nline';await vault.persist(binding,{text,revision:1,baseVersion:7},session,()=>true);const first=await vault.get(binding);await vault.persist(binding,{text:text+'2',revision:2,baseVersion:7},session,()=>true);const second=await vault.get(binding);const saved=JSON.stringify(second);return{pass:!saved.includes(text)&&!saved.includes(keyReply().key)&&!('digest'in second)&&!('key'in second)&&first.nonce!==second.nonce&&atob(second.nonce).length===12,nonceChanged:first.nonce!==second.nonce,metadataFields:Object.keys(second)};});});
 await probe('AAD tampering fails authenticated restore',async page=>{await init(page,'aad-review');return page.evaluate(async()=>{await vault.persist(binding,{text:'protected',revision:1,baseVersion:7},session,()=>true);await vault.transaction('readwrite',tx=>{const store=tx.objectStore('drafts');const request=store.openCursor();request.onsuccess=()=>{const cursor=request.result;if(cursor)cursor.update({...cursor.value,baseVersion:999});};});try{await vault.restore(binding,session,()=>true);return{pass:false,restored:true};}catch(e){return{pass:true,error:e.message};}});});
 console.log(JSON.stringify({summary:{total:results.length,passed:results.filter(r=>r.pass).length,failed:results.filter(r=>!r.pass).length},browser:browser.version()},null,2));
 if(results.some(r=>!r.pass))process.exitCode=1;
}finally{await browser?.close();await new Promise(r=>server.close(r));}
